[mgr]
ratio          = [ 1, 4, 3 ]
sort_by        = "mtime" # none mtime btime extension alphabetical natural size
sort_sensitive = false
sort_reverse 	 = true
sort_dir_first = true
sort_translit  = false
linemode       = "size"
show_hidden    = true 
show_symlink   = true
scrolloff      = 5
mouse_events   = [ "click", "scroll" ]
title_format   = "Yazi - {cwd}"

[preview]
wrap            = "yes"
tab_size        = 2
max_width       = 600
max_height      = 900
cache_dir       = ""
image_delay     = 30
image_filter    = "triangle"
image_quality   = 75
ueberzug_scale  = 1
ueberzug_offset = [ 0, 0, 0, 0 ]

[opener]
play = [
	{ run = 'mpv "$@"', orphan = true, for = "unix" },
]
edit = [
	{ run = '$EDITOR "$@"', block = true, for = "unix" },
]
open = [
	{ run = 'xdg-open "$@"', desc = "Open", for = "linux" },
]
extract = [
	{ run = 'file-roller "$@"', desc = "Open", for = "linux" },
]

[open]
rules = [
	{ mime = "text/*", use = ["edit", "open"] },
	{ name = "*.json", use = ["edit", "open"] },
	{ name = "*.html", use = [ "open", "edit" ] },
  { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", use = "extract" },
  { mime = "inode/empty", use = "edit" },
  { name = "*", use = "open" },
]


[tasks]
micro_workers    = 10
macro_workers    = 10
bizarre_retry    = 3
image_alloc      = 536870912  # 512MB
image_bound      = [ 5000, 5000 ]
suppress_preload = false

